tracer.property: "I am the default"
server.port: "8082"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform: "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/eagle_eye_local"
spring.datasource.username: "postgres"
spring.datasource.password: "{cipher}a028ddf4c4054ce4fe2ad246e61c4f14861cbcadcbe83fba10b43a6ff6b55f21"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"

# eureka config
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# cloud stream
spring:
 cloud:
  stream:
    bindings:
      # output is the name of your channel and maps to
      # the Source.output() channel
      output:
        # topic name
        destination: orgChangeTopic
        # Type of message being sent/received
        content: application/json
      kafka:
        binder:
          # zookeeper
          zkNodes: localhost
          brokers: localhost